for $x as xs:error in ()
return fn:true()
