try { fn:error() } catch * { count($err:module) }
