try { function () { fn:error() }() } catch err:FOER0000 { 0 }
