try {
  fn:error()
} catch * {
  $err:code
}
