try {
  0
} catch err:FOER0000 {
  fn:error()
}
