some $x in fn:error() satisfies false()
